### ISSUE TITLE
Add shorthand for BehaviourLinkHandler events

### ISSUE THREAD

**Issue by JaviCepa** [JuDelCo/Core#1]
Instead of typing:
`void Start()
{
    Core.Event.Subscribe<E_OnKeyPress>(new BehaviourLinkHandler(this), SelfDestruct);
}`

It'd be nice to just type:
`void Start()
{
    this.Subscribe<E_OnKeyPress>(SelfDestruct);
}`

Using a extension method like this one:
`public static void Subscribe<T>(this Behaviour behaviour, System.Action<T> Action)
{
    Core.Event.Subscribe<T>(new Ju.Handlers.BehaviourLinkHandler(behaviour), Action);
}`

**Comment by JuDelCo** [comment]
You can already do that 😄

```
using Ju.Extensions;

public class YourClass : MonoBehaviour
{
	private void Start()
	{
		this.EventSubscribe<E_OnKeyPress>(SelfDestruct);
	}

	// ...
}
```

**Comment by JuDelCo** [comment]
I forgot to say, if you want to do the same but in a custom service, the using statement is a bit different.

```
using Ju.Services.Extensions;

public class YourService : IService
{
	private void FooMethod()
	{
		this.EventSubscribe<E_OnKeyPress>(SelfDestruct);
	}

	// ...
}
```

**Comment by JaviCepa** [comment]
Thanks!
